import { motion } from "framer-motion";
import { HeartPulse, Salad, Dumbbell, ArrowRight } from "lucide-react";

const cards = [
  {
    icon: HeartPulse,
    title: "Wellness",
    desc: "Receive personalized health recommendations generated by AI.",
    gradient: "from-rose-500 to-pink-500",
    bg: "from-rose-500/10 to-pink-500/10",
    shadow: "shadow-rose-500/25",
    btn: "Explore Wellness",
  },
  {
    icon: Salad,
    title: "Healthy Recipes",
    desc: "Discover healthy meals based on your BMI and health profile.",
    gradient: "from-emerald-500 to-teal-500",
    bg: "from-emerald-500/10 to-teal-500/10",
    shadow: "shadow-emerald-500/25",
    btn: "View Recipes",
  },
  {
    icon: Dumbbell,
    title: "Fitness Goals",
    desc: "Generate personalized workout plans and track your progress.",
    gradient: "from-blue-500 to-violet-500",
    bg: "from-blue-500/10 to-violet-500/10",
    shadow: "shadow-blue-500/25",
    btn: "Start Fitness Journey",
  },
];

export default function ActionCards() {
  return (
    <section className="py-16 md:py-20">
      <div className="max-w-7xl mx-auto px-5 md:px-8 grid md:grid-cols-3 gap-6">
        {cards.map((c, i) => {
          const Icon = c.icon;
          return (
            <motion.div
              key={c.title}
              initial={{ opacity: 0, y: 40 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-80px" }}
              transition={{ duration: 0.5, delay: i * 0.1 }}
              whileHover={{ y: -8, scale: 1.02 }}
              className={`group relative rounded-3xl p-7 glass hover:shadow-2xl ${c.shadow} transition-all duration-300 overflow-hidden`}
            >
              {/* Animated gradient background on hover */}
              <div
                className={`absolute inset-0 bg-gradient-to-br ${c.bg} opacity-0 group-hover:opacity-100 transition-opacity duration-500`}
              />
              <div className="absolute -top-12 -right-12 w-40 h-40 rounded-full bg-gradient-to-br opacity-0 group-hover:opacity-30 blur-3xl transition-opacity duration-500"
                style={{ backgroundImage: `linear-gradient(to bottom right, var(--tw-gradient-stops))` }}
              />

              <div className="relative">
                <div className={`w-14 h-14 rounded-2xl bg-gradient-to-br ${c.gradient} flex items-center justify-center shadow-lg ${c.shadow} group-hover:scale-110 group-hover:rotate-3 transition-transform duration-300`}>
                  <Icon className="w-7 h-7 text-white" />
                </div>

                <h3 className="mt-5 text-xl font-bold text-slate-900 dark:text-white">
                  {c.title}
                </h3>
                <p className="mt-2 text-sm text-slate-600 dark:text-slate-300 leading-relaxed">
                  {c.desc}
                </p>

                <button className="mt-6 inline-flex items-center gap-1.5 text-sm font-semibold text-slate-800 dark:text-slate-100 group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors">
                  {c.btn}
                  <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                </button>
              </div>
            </motion.div>
          );
        })}
      </div>
    </section>
  );
}
