/**
 * ai/wellnessAI.js
 * ----------------
 * Core "AI" logic for the Wellness Assistant.
 *
 * Chat replies are generated by a real LLM via the OpenRouter API
 * (https://openrouter.ai), constrained to health & wellness topics by a
 * strict system prompt. If OPENROUTER_API_KEY is not set, or the API call
 * fails for any reason (network issue, rate limit, etc.), this module falls
 * back to the original rule-based replies so the chat never breaks.
 *
 * This module has no dependency on Express, so it can be:
 *   - imported directly by the backend (see backend/src/controllers/chatController.js)
 *   - unit tested on its own
 *   - reused by anything else that needs BMI or chat-reply logic
 */
require("dotenv").config({ path: __dirname + "/.env" });

const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY || "";
const OPENROUTER_MODEL = process.env.OPENROUTER_MODEL || "openai/gpt-4o-mini";
const OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions";

const SYSTEM_PROMPT = `You are an AI Healthcare and Medical Assistant.

Your role is to provide accurate, evidence-based, educational information on ALL healthcare and medical topics.

You can answer questions about:

- Human anatomy and physiology
- Diseases and medical conditions
- Symptoms and possible causes
- Medical diagnosis (educational explanation only)
- Medications and drug information
- Drug interactions
- Vaccinations
- Medical tests and laboratory reports
- Nutrition and diet
- Vitamins and minerals
- Exercise and fitness
- Weight management
- BMI
- Mental health
- Women's health
- Men's health
- Pregnancy
- Child health
- Elderly care
- First aid
- Emergency awareness
- Diabetes
- Hypertension
- Heart disease
- Cancer awareness
- Respiratory diseases
- Digestive disorders
- Kidney diseases
- Liver diseases
- Skin diseases
- Bone and joint disorders
- Neurological disorders
- Infectious diseases
- Allergies
- Sleep
- Hydration
- Preventive healthcare
- Healthy lifestyle
- Healthcare education

Instructions:

1. Answer every healthcare and medical question clearly, accurately, and professionally.

2. Explain medical concepts in simple language unless the user requests technical details.

3. If users describe symptoms:
   - Explain possible causes.
   - Mention common and serious possibilities.
   - Recommend seeing a healthcare professional when appropriate.
   - Never claim a diagnosis is certain.

4. For medication questions:
   - Explain uses.
   - Common side effects.
   - Precautions.
   - Drug interactions.
   - Never prescribe medications.

5. If users mention emergency symptoms such as:
   chest pain,
   difficulty breathing,
   stroke symptoms,
   severe bleeding,
   unconsciousness,
   seizures,
   suicidal thoughts,

   immediately advise them to seek emergency medical care.

6. Never invent medical facts.

7. If evidence is uncertain, clearly say so.

8. Never claim to replace a licensed healthcare professional.

9. Respond with empathy and professionalism.

10. Only refuse requests that are dangerous, illegal, or completely unrelated to healthcare and medicine.
`;
/** Compute BMI (metric): weight in kg, height in cm */
function computeBMI(heightCm, weightKg) {
  const h = Number(heightCm);
  const w = Number(weightKg);
  if (!h || !w || h <= 0 || w <= 0) return 0;
  return +(w / Math.pow(h / 100, 2)).toFixed(1);
}

/** Classify a BMI value into a category + short guidance hint */
function bmiCategory(bmi) {
  if (!bmi || !isFinite(bmi)) {
    return { label: "Unknown", category: "unknown", hint: "" };
  }
  if (bmi < 18.5) {
    return { label: "Underweight", category: "underweight", hint: "Gain weight healthily" };
  }
  if (bmi < 25) {
    return { label: "Healthy", category: "healthy", hint: "Maintain your routine" };
  }
  if (bmi < 30) {
    return { label: "Overweight", category: "overweight", hint: "Gradual weight loss recommended" };
  }
  return { label: "Obese", category: "obese", hint: "Medical guidance advised" };
}

/** Rule-based fallback reply (used if OpenRouter is unavailable or unconfigured) */
function ruleBasedReply(message, context = {}) {
  const lower = (message || "").toLowerCase();
  const firstName = context.name ? context.name.split(" ")[0] : null;
  const bmi = context.profile?.bmi;

  const named = (base) =>
    firstName && Math.random() > 0.35 ? `${firstName}, ${base}` : base;

  if (/bmi|weight|overweight|underweight/.test(lower)) {
    const bmiNote = bmi ? ` Your current BMI is ${bmi} (${bmiCategory(bmi).label}).` : "";
    return `Based on your profile${firstName ? `, ${firstName}` : ""}, I recommend a balanced routine: 30 minutes of moderate activity daily, whole-food meals, and consistent sleep.${bmiNote} Want me to craft a personalized plan?`;
  }
  if (/sleep|insomnia|tired/.test(lower)) {
    return named("for better sleep, try dimming the lights an hour before bed, avoid screens, and enjoy a warm cup of chamomile tea. Consistency is key.");
  }
  if (/water|hydrat/.test(lower)) {
    return named("aim for around 2L of water a day. Add cucumber or lemon slices if plain water feels boring!");
  }
  if (/stress|anxious|anxiety|mental/.test(lower)) {
    return named("mindfulness matters — even 5 minutes of deep breathing can reduce stress by up to 30%. You've got this 💛");
  }
  if (/food|diet|recipe|eat|nutrition/.test(lower)) {
    return named("focus on colorful plates: half vegetables, a quarter lean protein, a quarter whole grains. I can suggest recipes tailored to your BMI.");
  }
  if (/workout|exercise|gym|fitness/.test(lower)) {
    return named("a great weekly mix is 150 minutes of cardio plus 2–3 strength sessions. Let me tailor a plan for you.");
  }
  if (/hi|hello|hey/.test(lower)) {
    return firstName ? `Hi ${firstName}! Great to see you. What would you like to focus on today?` : "Hi there! What would you like to focus on today?";
  }
  if (/thank/.test(lower)) {
    return firstName ? `You're very welcome, ${firstName}! 💙 Keep up the great work.` : "You're very welcome! 💙 Keep up the great work.";
  }
  return "I'm a Wellness AI Assistant and can only help with health and wellness-related topics such as nutrition, fitness, BMI, exercise, sleep, hydration, stress management, mental wellness, and healthy lifestyle guidance. Please ask a question related to these topics.";
}

/**
 * Call OpenRouter's chat completions API with the wellness system prompt.
 * Returns the reply text, or null if the call could not be completed.
 */
async function callOpenRouter(message, context = {}) {
  if (!OPENROUTER_API_KEY) return null;

  const profileLine = context.profile
    ? `The user's profile — BMI: ${context.profile.bmi ?? "unknown"}, gender: ${context.profile.gender ?? "unknown"}, medical history: ${context.profile.history || "none provided"}.`
    : "";
  const nameLine = context.name ? `The user's name is ${context.name}.` : "";

  try {
    const res = await fetch(OPENROUTER_URL, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${OPENROUTER_API_KEY}`,
        "Content-Type": "application/json",
        // Optional but recommended by OpenRouter for attribution/rate-limit tiers:
        "HTTP-Referer": process.env.OPENROUTER_SITE_URL || "http://localhost",
        "X-Title": "AI Wellness Assistant",
      },
      body: JSON.stringify({
        model: OPENROUTER_MODEL,
        messages: [
          { role: "system", content: `${SYSTEM_PROMPT}\n\n${nameLine} ${profileLine}`.trim() },
          { role: "user", content: message },
        ],
        temperature: 0.6,
        max_tokens: 400,
      }),
    });

    if (!res.ok) {
      console.error("OpenRouter API error:", res.status, await res.text().catch(() => ""));
      return null;
    }

    const data = await res.json();
    const reply = data?.choices?.[0]?.message?.content?.trim();
    return reply || null;
  } catch (err) {
    console.error("OpenRouter request failed:", err.message);
    return null;
  }
}

/**
 * Generate a chat reply. Tries OpenRouter first; falls back to the
 * rule-based reply if the API key is missing or the call fails.
 * @param {string} message - the user's message
 * @param {object} context - optional context: { name, profile: { bmi, gender, history } }
 */
async function getChatReply(message, context = {}) {
  const llmReply = await callOpenRouter(message, context);

  if (llmReply) {
    return llmReply;
  }

  // OpenRouter unavailable (no key, network issue, rate limit, etc.) —
  // fall back to the rule-based reply so the chat never breaks.
  return ruleBasedReply(message, context);
}

/** Build the opening greeting message for a (possibly signed-in) user */
function getGreeting(name) {
  if (name) {
    const first = name.split(" ")[0];
    return `Hello ${first}! 👋 How can I help you today? I can share tips on nutrition, fitness, sleep, or mental wellness — just ask!`;
  }
  return "Hi there! 👋 I'm your WellnessAI assistant. Sign up to get a personalized experience, or ask me anything about nutrition, fitness, sleep, or mental health. 🌱";
}

module.exports = {
  computeBMI,
  bmiCategory,
  getChatReply,
  getGreeting,
};
